package hc.candlecraft.candlecraftultimate.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF974810)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDBC9)
val md_theme_light_onPrimaryContainer = Color(0xFF331200)
val md_theme_light_secondary = Color(0xFF3A54C4)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFDDE1FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001356)
val md_theme_light_tertiary = Color(0xFF705D00)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFE173)
val md_theme_light_onTertiaryContainer = Color(0xFF221B00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF311300)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF311300)
val md_theme_light_surfaceVariant = Color(0xFFF4DED4)
val md_theme_light_onSurfaceVariant = Color(0xFF52443C)
val md_theme_light_outline = Color(0xFF85746B)
val md_theme_light_inverseOnSurface = Color(0xFFFFEDE4)
val md_theme_light_inverseSurface = Color(0xFF512400)
val md_theme_light_inversePrimary = Color(0xFFFFB68E)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF974810)
val md_theme_light_outlineVariant = Color(0xFFD7C2B8)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB68E)
val md_theme_dark_onPrimary = Color(0xFF532200)
val md_theme_dark_primaryContainer = Color(0xFF763300)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDBC9)
val md_theme_dark_secondary = Color(0xFFB9C3FF)
val md_theme_dark_onSecondary = Color(0xFF002389)
val md_theme_dark_secondaryContainer = Color(0xFF1C3AAB)
val md_theme_dark_onSecondaryContainer = Color(0xFFDDE1FF)
val md_theme_dark_tertiary = Color(0xFFE4C54A)
val md_theme_dark_onTertiary = Color(0xFF3B2F00)
val md_theme_dark_tertiaryContainer = Color(0xFF554600)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFE173)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF311300)
val md_theme_dark_onBackground = Color(0xFFFFDBC7)
val md_theme_dark_surface = Color(0xFF311300)
val md_theme_dark_onSurface = Color(0xFFFFDBC7)
val md_theme_dark_surfaceVariant = Color(0xFF52443C)
val md_theme_dark_onSurfaceVariant = Color(0xFFD7C2B8)
val md_theme_dark_outline = Color(0xFF9F8D84)
val md_theme_dark_inverseOnSurface = Color(0xFF311300)
val md_theme_dark_inverseSurface = Color(0xFFFFDBC7)
val md_theme_dark_inversePrimary = Color(0xFF974810)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB68E)
val md_theme_dark_outlineVariant = Color(0xFF52443C)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFFFBA94)


val ButtonColor = Color(0xFFCA809E)

val BackgroundColorDarker = Color(0xFF8A7251)
val BackgroundColorDark = Color(0xFFAF946D)
val BackgroundColor = Color(0xFFcaac80)
val BackgroundColorLight = Color(0xFFDABC91)
val BackgroundColorLighter = Color(0xFFE9CCA1)


val RecipeItemForegroundColor = Color(0xFFD2DAE9)

val BackgroundColorLightBlue = Color(0xFFE4ECFC)
val BackgroundColorLightRed = Color(0xFFFFE6E6)
val BackgroundColorLightGreen = Color(0xFFDDFFE6)
val BackgroundColorLightPink = Color(0xFFFBE4FF)

val BackgroundColorDarkBlue = Color(0xFF272E3D)
val BackgroundColorDarkRed = Color(0xFF412828)
val BackgroundColorDarkGreen = Color(0xFF223125)
val BackgroundColorDarkPink = Color(0xFF342136)